// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANhDq_MMOKnbuRZ4C-su9MyFQL0HyEdDM',
    appId: '1:486751830571:web:18a20a9dcde9fc5398206e',
    messagingSenderId: '486751830571',
    projectId: 'jarnama-31deb',
    authDomain: 'jarnama-31deb.firebaseapp.com',
    storageBucket: 'jarnama-31deb.appspot.com',
    measurementId: 'G-ERKZJ3PFBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX8IMsCkdPK_E_xYbDT_1Xk_hAc_2-bzI',
    appId: '1:486751830571:android:61389bfa004ffc7898206e',
    messagingSenderId: '486751830571',
    projectId: 'jarnama-31deb',
    storageBucket: 'jarnama-31deb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2huh0fCIMFKo75nSj79-8LEMK3zFNfzs',
    appId: '1:486751830571:ios:ad9cb1c05e3392ee98206e',
    messagingSenderId: '486751830571',
    projectId: 'jarnama-31deb',
    storageBucket: 'jarnama-31deb.appspot.com',
    iosClientId: '486751830571-jv7qain7cvhch0ejnuhc534a3j4a26j5.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2huh0fCIMFKo75nSj79-8LEMK3zFNfzs',
    appId: '1:486751830571:ios:ad9cb1c05e3392ee98206e',
    messagingSenderId: '486751830571',
    projectId: 'jarnama-31deb',
    storageBucket: 'jarnama-31deb.appspot.com',
    iosClientId: '486751830571-jv7qain7cvhch0ejnuhc534a3j4a26j5.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnama',
  );
}
