// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyRB9Jx4DIwfJBFzQvVLaAoFajH3a2d9M',
    appId: '1:41012077226:web:5b32fdc26137e2471f66d3',
    messagingSenderId: '41012077226',
    projectId: 'jarnama-7fa58',
    authDomain: 'jarnama-7fa58.firebaseapp.com',
    storageBucket: 'jarnama-7fa58.appspot.com',
    measurementId: 'G-T6RWMBCJ2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqgPL2EPQhcaNJpIJ-tNVqBJOQlL3iuZU',
    appId: '1:41012077226:android:09a623aad521a2301f66d3',
    messagingSenderId: '41012077226',
    projectId: 'jarnama-7fa58',
    storageBucket: 'jarnama-7fa58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByd6qyl-PRZJ99QqP5qP4YLYDgbTI06y0',
    appId: '1:41012077226:ios:78593ae8343f01781f66d3',
    messagingSenderId: '41012077226',
    projectId: 'jarnama-7fa58',
    storageBucket: 'jarnama-7fa58.appspot.com',
    iosClientId: '41012077226-dab9v2bcjb38muvj6qdk43s8lul8eobs.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByd6qyl-PRZJ99QqP5qP4YLYDgbTI06y0',
    appId: '1:41012077226:ios:78593ae8343f01781f66d3',
    messagingSenderId: '41012077226',
    projectId: 'jarnama-7fa58',
    storageBucket: 'jarnama-7fa58.appspot.com',
    iosClientId: '41012077226-dab9v2bcjb38muvj6qdk43s8lul8eobs.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnama',
  );
}
